# This is a basic workflow to help you get started with Actions

name: BuildPlugin

# Controls when the action will run. 
on:
  push:
    branches: [ "1.1","6.0" ]
  pull_request:
    branches: [ "1.1","6.0" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run gradle buildPlugin
        run: ./gradlew buildPlugin
      
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.2.1
        with:
          name: ScriptAgent-SNAPSHOT.jar
          path: build/libs
