name: Check Scripts

on:
  push:
    branches-ignore:
      - 'private*'
  pull_request:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Validate Gradle wrapper
        uses: gradle/actions/wrapper-validation@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          cache-read-only: ${{ startsWith(github.ref, 'refs/tags/') }}

      # 保留自定义缓存（如果需要）
      - uses: actions/cache@v4
        with:
          path: libs
          key: sa-deps-${{ hashFiles('scripts/build.gradle.kts') }}
          restore-keys: |
            sa-deps-
      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT
      - uses: actions/cache@v4
        with:
          path: |
            scripts/cache
          key: kts-cache-${{ steps.date.outputs.date }}
          restore-keys: |
            kts-cache-

      - name: Run precompile
        run: ./gradlew precompile